### ISSUE TITLE
Request for clarification...

### ISSUE THREAD

**Issue by neuronsong** [kicsipixel/Inventory#1]
Hi... I'm searching for any and all Cappuccino projects in an attempt to learn Cappuccino and Objective-J.  This is one of the few projects I've found that clearly shows the use of CPURLConnection.  Thanks so much for making this available!

I was wondering if you could include a data.php file in the current directory with a small example of the json to be displayed?  That way anyone wanting to look at this project can use "python -m SimpleHTTPServer" in the current directory and connect to "http://localhost:8000/data.php" and the project will just work.

**Comment by neuronsong** [comment]
Never mind... I figured it out...

**Comment by kicsipixel** [comment]
I usually use Sinatra to serve JSON. I can share that.
